In [55]:
import pandas
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
import warnings
warnings.filterwarnings('ignore')

In [43]:
train_df=pd.read_csv('review_ratings_prediction.csv')
train_df

Unnamed: 0  reviews.rating  \
0              0             5.0   
1              1             4.0   
2              2             4.0   
3              3             5.0   
4              4             5.0   
...          ...             ...   
7294        7294             4.0   
7295        7295             4.0   
7296        7296             4.0   
7297        7297             5.0   
7298        7298             4.0   

                                           reviews.text  
0     This keyboard is very easy to type on, but the...  
1     It's thin and light. I can type pretty easily ...  
2     I love the new design the keys are spaced well...  
3     Attached easily and firmly. Has a nice feel. A...  
4     Our original keyboard was okay, but did not ha...  
...                                                 ...  
7294  This remote was a decent replacement for my lo...  
7295  This looks good on my celling. Flushes very we...  
7296  Great Plate for projector mount, very easy to ...  
7297  This mount worked very well for me when I used...  
7298  It's a nice solid mounting plate check and mak...  

[7299 rows x 3 columns]

In [44]:
train_df.drop(['Unnamed: 0'],axis=1,inplace=True)
train_df

reviews.rating                                       reviews.text
0                5.0  This keyboard is very easy to type on, but the...
1                4.0  It's thin and light. I can type pretty easily ...
2                4.0  I love the new design the keys are spaced well...
3                5.0  Attached easily and firmly. Has a nice feel. A...
4                5.0  Our original keyboard was okay, but did not ha...
...              ...                                                ...
7294             4.0  This remote was a decent replacement for my lo...
7295             4.0  This looks good on my celling. Flushes very we...
7296             4.0  Great Plate for projector mount, very easy to ...
7297             5.0  This mount worked very well for me when I used...
7298             4.0  It's a nice solid mounting plate check and mak...

[7299 rows x 2 columns]

In [45]:
train_df.head()

reviews.rating                                       reviews.text
0             5.0  This keyboard is very easy to type on, but the...
1             4.0  It's thin and light. I can type pretty easily ...
2             4.0  I love the new design the keys are spaced well...
3             5.0  Attached easily and firmly. Has a nice feel. A...
4             5.0  Our original keyboard was okay, but did not ha...

In [46]:
train_df.tail()

reviews.rating                                       reviews.text
7294             4.0  This remote was a decent replacement for my lo...
7295             4.0  This looks good on my celling. Flushes very we...
7296             4.0  Great Plate for projector mount, very easy to ...
7297             5.0  This mount worked very well for me when I used...
7298             4.0  It's a nice solid mounting plate check and mak...

In [47]:
train_df.isnull().sum()

reviews.rating    164
reviews.text        5
dtype: int64

In [48]:
train_df.dropna(inplace=True)


In [49]:
train_df.isnull().sum()

reviews.rating    0
reviews.text      0
dtype: int64

In [50]:
print('train shape is ',train_df.shape,)
print('train info',train_df.info)

train shape is  (7130, 2)
train info <bound method DataFrame.info of       reviews.rating                                       reviews.text
0                5.0  This keyboard is very easy to type on, but the...
1                4.0  It's thin and light. I can type pretty easily ...
2                4.0  I love the new design the keys are spaced well...
3                5.0  Attached easily and firmly. Has a nice feel. A...
4                5.0  Our original keyboard was okay, but did not ha...
...              ...                                                ...
7294             4.0  This remote was a decent replacement for my lo...
7295             4.0  This looks good on my celling. Flushes very we...
7296             4.0  Great Plate for projector mount, very easy to ...
7297             5.0  This mount worked very well for me when I used...
7298             4.0  It's a nice solid mounting plate check and mak...

[7130 rows x 2 columns]>


In [51]:
print('train data Set descriptin',train_df.describe())

train data Set descriptin        reviews.rating
count     7130.000000
mean         4.371950
std          1.038844
min          1.000000
25%          4.000000
50%          5.000000
75%          5.000000
max          5.000000


In [52]:
x=train_df.drop(['reviews.rating'],axis=1)
x

reviews.text
0     This keyboard is very easy to type on, but the...
1     It's thin and light. I can type pretty easily ...
2     I love the new design the keys are spaced well...
3     Attached easily and firmly. Has a nice feel. A...
4     Our original keyboard was okay, but did not ha...
...                                                 ...
7294  This remote was a decent replacement for my lo...
7295  This looks good on my celling. Flushes very we...
7296  Great Plate for projector mount, very easy to ...
7297  This mount worked very well for me when I used...
7298  It's a nice solid mounting plate check and mak...

[7130 rows x 1 columns]

In [53]:
y=train_df.iloc[:,0]
y

0       5.0
1       4.0
2       4.0
3       5.0
4       5.0
       ... 
7294    4.0
7295    4.0
7296    4.0
7297    5.0
7298    4.0
Name: reviews.rating, Length: 7130, dtype: float64

In [54]:
port_stem=PorterStemmer()

In [57]:
def stemming(content):
    stemmed_content = re.sub('[^a-zA-z]',' ',content)##will remove all the data other than alphabates like (,''@numeric)###
    stemmed_content = stemmed_content.lower() ##converting all letters to lowercase for making machine to understand easily#
    stemmed_content = stemmed_content.split()
   # stemmed_content = [port_stem(word) for word in  stemmed_content if not word in stopwords.words('english')]
    stemmed_content = ' '.join(stemmed_content)
    return stemmed_content

In [59]:
 train_df['reviews.text']=train_df['reviews.text'].apply(stemming)

In [61]:
print(train_df['reviews.text'])

0       this keyboard is very easy to type on but the ...
1       it s thin and light i can type pretty easily o...
2       i love the new design the keys are spaced well...
3       attached easily and firmly has a nice feel a m...
4       our original keyboard was okay but did not hav...
                              ...                        
7294    this remote was a decent replacement for my lo...
7295    this looks good on my celling flushes very wel...
7296    great plate for projector mount very easy to i...
7297    this mount worked very well for me when i used...
7298    it s a nice solid mounting plate check and mak...
Name: reviews.text, Length: 7130, dtype: object


In [64]:
x=train_df['reviews.text']
x

0       this keyboard is very easy to type on but the ...
1       it s thin and light i can type pretty easily o...
2       i love the new design the keys are spaced well...
3       attached easily and firmly has a nice feel a m...
4       our original keyboard was okay but did not hav...
                              ...                        
7294    this remote was a decent replacement for my lo...
7295    this looks good on my celling flushes very wel...
7296    great plate for projector mount very easy to i...
7297    this mount worked very well for me when i used...
7298    it s a nice solid mounting plate check and mak...
Name: reviews.text, Length: 7130, dtype: object

In [65]:
feature_extraction= TfidfVectorizer (min_df=1,stop_words='english',lowercase="True")
x=feature_extraction.fit_transform(x)

In [66]:
print (x)

  (0, 5249)	0.3940318765354132
  (0, 8177)	0.4813880783230859
  (0, 72)	0.3798286746143133
  (0, 3372)	0.2639021777267799
  (0, 868)	0.21019804566657024
  (0, 7155)	0.3293513836547713
  (0, 3461)	0.2662696853363856
  (0, 9476)	0.2941626410669594
  (0, 2851)	0.16162036834538535
  (0, 4906)	0.25076346692471385
  (1, 2849)	0.4976631046007105
  (1, 6795)	0.4682230049417139
  (1, 5153)	0.5189644466617721
  (1, 9476)	0.5135898704838082
  (2, 6835)	0.2122321005253102
  (2, 8871)	0.21049739437971196
  (2, 9692)	0.1278955720802551
  (2, 6108)	0.25545284565102766
  (2, 10131)	0.16559109711707204
  (2, 7234)	0.2971991959991393
  (2, 6822)	0.28136865695505575
  (2, 3457)	0.25545284565102766
  (2, 9480)	0.3235283210097429
  (2, 5650)	0.4318616669731493
  (2, 8433)	0.3311746049488053
  :	:
  (7128, 1641)	0.5509987301882397
  (7128, 1364)	0.21931928399993356
  (7128, 6901)	0.224333228389627
  (7128, 6433)	0.2633297763761037
  (7128, 156)	0.40439001672439034
  (7128, 6591)	0.22719385848002036
  (7128,

In [75]:
import sklearn
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.model_selection import train_test_split

In [76]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.30,stratify=y,random_state=20)

In [79]:
rf=RandomForestClassifier(n_estimators=100,random_state=50)
svm=SVC()
lg=LogisticRegression()
dt=DecisionTreeClassifier()
knn=KNeighborsClassifier()
model=[rf,svm,lg,dt,knn]
for m in model:
    m.fit(x_train,y_train)
    predm=m.predict(x_train)
    print('Training accuracy is {}'.format(accuracy_score(y_train,predm)))
    predm=m.predict(x_test)
    print('accuracy_score of',m ,'is:')
    print(accuracy_score(y_test,predm))
    print(confusion_matrix(y_test,predm))
    print(classification_report(y_test,predm))

Training accuracy is 0.9985974754558204
accuracy_score of RandomForestClassifier(random_state=50) is:
0.6470313230481534
[[   5    0    1    8   81]
 [   2    0    1   12   52]
 [   1    1    4   16  110]
 [   0    1    0   54  443]
 [   0    0    1   25 1321]]
              precision    recall  f1-score   support

         1.0       0.62      0.05      0.10        95
         2.0       0.00      0.00      0.00        67
         3.0       0.57      0.03      0.06       132
         4.0       0.47      0.11      0.18       498
         5.0       0.66      0.98      0.79      1347

    accuracy                           0.65      2139
   macro avg       0.46      0.23      0.22      2139
weighted avg       0.59      0.65      0.54      2139

Training accuracy is 0.8974153476257263
accuracy_score of SVC() is:
0.6465638148667602
[[   3    0    1    9   82]
 [   0    0    0    8   59]
 [   2    0    2   18  110]
 [   1    0    0   49  448]
 [   0    0    0   18 1329]]
              precisi

In [81]:
import joblib

In [82]:
joblib.dump(lg,'ratings_prediction.obj')

['ratings_prediction.obj']